package com.methodminer.export;

import com.methodminer.comparison.CoverageStatus;
import com.methodminer.comparison.OperationRoleCoverage;
import com.methodminer.comparison.RoleComparisonResult;
import com.methodminer.core.model.ApiSurface;
import com.methodminer.core.model.Role;
import com.methodminer.core.model.SessionProfile;
import com.methodminer.core.repository.InMemorySurfaceRepository;
import com.methodminer.payload.PayloadAssemblyResult;
import com.methodminer.payload.PayloadCandidate;
import com.methodminer.payload.PayloadCandidateType;
import com.methodminer.payload.PayloadVariable;
import com.methodminer.protocol.ProtocolKind;
import com.methodminer.risk.RiskConfidence;
import com.methodminer.risk.RiskSignal;
import com.methodminer.risk.RiskSignalCategory;
import com.methodminer.risk.RiskSignalResult;
import com.methodminer.risk.RiskSeverity;
import com.methodminer.session.InMemorySessionRepository;
import com.methodminer.session.SessionFingerprint;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.time.Instant;
import java.util.*;

import static org.junit.jupiter.api.Assertions.*;

/**
 * Comprehensive tests for {@link IntelligenceExporter}.
 */
class IntelligenceExporterTest {

    private IntelligenceExporter exporter;
    private ApiSurface surface;
    private InMemorySessionRepository sessionRepo;

    @BeforeEach
    void setUp() {
        exporter = new IntelligenceExporter();
        InMemorySurfaceRepository surfaceRepo = new InMemorySurfaceRepository("test-project");
        surface = surfaceRepo.snapshot();
        sessionRepo = new InMemorySessionRepository();
    }

    // ---- Empty Export --------------------------------------------------------

    @Test
    void emptyExportGeneratesMarkdownOnly() {
        ExportResult result = exporter.export(surface, List.of(), null, null, null,
                ExportOptions.DEFAULTS);
        assertFalse(result.artifacts().isEmpty());
        assertEquals(1, result.artifacts().size()); // Just Markdown
        assertEquals(ExportFormat.MARKDOWN, result.artifacts().get(0).format());
    }

    @Test
    void emptyExportHasValidMetadata() {
        ExportResult result = exporter.export(surface, List.of(), null, null, null,
                ExportOptions.DEFAULTS);
        assertNotNull(result.exportedAt());
        assertTrue(result.totalBytes() > 0);
        assertFalse(result.summary().isBlank());
    }

    // ---- Markdown Report ----------------------------------------------------

    @Test
    void markdownContainsExecutiveSummary() {
        ExportResult result = exporter.export(surface, List.of(), null, null, null,
                ExportOptions.DEFAULTS);
        String md = result.artifacts().get(0).content();
        assertTrue(md.contains("# Method Miner Intelligence Report"));
        assertTrue(md.contains("## Executive Summary"));
        assertTrue(md.contains("Generated by Method Miner"));
    }

    @Test
    void markdownContainsSessions() {
        SessionFingerprint fp = new SessionFingerprint("host.com", "Bearer", "hash1", "admin@test.com", "",
                Set.of(), Set.of("Authorization"), Map.of());
        SessionProfile profile = sessionRepo.upsert(fp, Instant.now());
        sessionRepo.setRole(profile.id(), Role.ADMIN);

        ExportResult result = exporter.export(surface, sessionRepo.snapshot(), null, null, null,
                ExportOptions.DEFAULTS);
        String md = result.artifacts().get(0).content();
        assertTrue(md.contains("## Session Profiles"));
        assertTrue(md.contains("admin@test.com"));
        assertTrue(md.contains("ADMIN"));
    }

    @Test
    void markdownContainsComparison() {
        OperationRoleCoverage orc = new OperationRoleCoverage(
                UUID.randomUUID(), ProtocolKind.JSON_RPC, "host.com", "/rpc",
                "DeleteDevice", CoverageStatus.ADMIN_ONLY, 2, 0, 0,
                Set.of("id"), List.of());
        RoleComparisonResult comparison = new RoleComparisonResult(
                Instant.now(), 2, 1, List.of(orc),
                Map.of(CoverageStatus.ADMIN_ONLY, 1));

        ExportResult result = exporter.export(surface, List.of(), comparison, null, null,
                ExportOptions.DEFAULTS);
        String md = result.artifacts().get(0).content();
        assertTrue(md.contains("## Role Comparison"));
        assertTrue(md.contains("DeleteDevice"));
        assertTrue(md.contains("ADMIN_ONLY"));
    }

    @Test
    void markdownContainsRiskSignals() {
        RiskSignalResult signals = buildSignalResult();

        ExportResult result = exporter.export(surface, List.of(), null, signals, null,
                ExportOptions.DEFAULTS);
        String md = result.artifacts().get(0).content();
        assertTrue(md.contains("## Risk Signals"));
        assertTrue(md.contains("DeleteDevice"));
        assertTrue(md.contains("### Signal Details"));
    }

    @Test
    void markdownContainsPayloads() {
        PayloadAssemblyResult payloads = buildPayloadResult();

        ExportResult result = exporter.export(surface, List.of(), null, null, payloads,
                ExportOptions.DEFAULTS);
        String md = result.artifacts().get(0).content();
        assertTrue(md.contains("## Payloads"));
        assertTrue(md.contains("Replay DeleteDevice"));
    }

    // ---- JSON Export --------------------------------------------------------

    @Test
    void jsonExportGeneratedWhenSignalsPresent() {
        RiskSignalResult signals = buildSignalResult();

        ExportResult result = exporter.export(surface, List.of(), null, signals, null,
                ExportOptions.DEFAULTS);
        long jsonCount = result.artifacts().stream()
                .filter(a -> a.format() == ExportFormat.JSON).count();
        assertEquals(1, jsonCount);
    }

    @Test
    void jsonExportIsValidArray() {
        RiskSignalResult signals = buildSignalResult();

        ExportResult result = exporter.export(surface, List.of(), null, signals, null,
                ExportOptions.DEFAULTS);
        ExportArtifact json = result.artifacts().stream()
                .filter(a -> a.format() == ExportFormat.JSON).findFirst().orElseThrow();
        assertTrue(json.content().startsWith("["));
        assertTrue(json.content().trim().endsWith("]"));
        assertTrue(json.content().contains("\"operation\": \"DeleteDevice\""));
    }

    // ---- JSONL Export -------------------------------------------------------

    @Test
    void jsonlExportHasOneLinePerSignal() {
        RiskSignalResult signals = buildSignalResult();

        ExportResult result = exporter.export(surface, List.of(), null, signals, null,
                ExportOptions.DEFAULTS);
        ExportArtifact jsonl = result.artifacts().stream()
                .filter(a -> a.format() == ExportFormat.JSONL && a.fileName().contains("signal"))
                .findFirst().orElseThrow();
        String[] lines = jsonl.content().split("\n");
        assertEquals(signals.signals().size(), lines.length);
        assertTrue(lines[0].startsWith("{"));
    }

    @Test
    void payloadJsonlExportGenerated() {
        PayloadAssemblyResult payloads = buildPayloadResult();

        ExportResult result = exporter.export(surface, List.of(), null, null, payloads,
                ExportOptions.DEFAULTS);
        long payloadJsonlCount = result.artifacts().stream()
                .filter(a -> a.format() == ExportFormat.JSONL && a.fileName().contains("payload"))
                .count();
        assertEquals(1, payloadJsonlCount);
    }

    // ---- CSV Export ---------------------------------------------------------

    @Test
    void csvExportHasHeaderAndData() {
        RiskSignalResult signals = buildSignalResult();

        ExportResult result = exporter.export(surface, List.of(), null, signals, null,
                ExportOptions.DEFAULTS);
        ExportArtifact csv = result.artifacts().stream()
                .filter(a -> a.format() == ExportFormat.CSV && a.fileName().contains("signal"))
                .findFirst().orElseThrow();
        assertTrue(csv.content().startsWith("Score,Severity,Confidence,Category"));
        String[] lines = csv.content().split("\n");
        assertTrue(lines.length > 1); // header + data
    }

    @Test
    void sessionCsvExportGenerated() {
        SessionFingerprint fp = new SessionFingerprint("host.com", "Bearer", "hash1", "user@test.com", "",
                Set.of("sid"), Set.of("Authorization"), Map.of());
        sessionRepo.upsert(fp, Instant.now());

        ExportResult result = exporter.export(surface, sessionRepo.snapshot(), null, null, null,
                ExportOptions.DEFAULTS);
        long sessionCsvCount = result.artifacts().stream()
                .filter(a -> a.format() == ExportFormat.CSV && a.fileName().contains("session"))
                .count();
        assertEquals(1, sessionCsvCount);
    }

    // ---- Export Options ------------------------------------------------------

    @Test
    void excludeSessionsHidesSessionSection() {
        SessionFingerprint fp = new SessionFingerprint("host.com", "Bearer", "hash1", "admin@test.com", "",
                Set.of(), Set.of(), Map.of());
        sessionRepo.upsert(fp, Instant.now());

        ExportOptions noSessions = new ExportOptions(
                false, true, true, true, true, true, false, "test");

        ExportResult result = exporter.export(surface, sessionRepo.snapshot(), null, null, null,
                noSessions);
        String md = result.artifacts().get(0).content();
        assertFalse(md.contains("## Session Profiles"));
        // Also no sessions CSV
        assertEquals(0, result.artifacts().stream()
                .filter(a -> a.fileName().contains("session")).count());
    }

    @Test
    void excludeTimestampsHidesDates() {
        SessionFingerprint fp = new SessionFingerprint("host.com", "Bearer", "hash1", "admin@test.com", "",
                Set.of(), Set.of(), Map.of());
        sessionRepo.upsert(fp, Instant.now());

        ExportOptions noTimestamps = new ExportOptions(
                true, true, true, true, true, false, false, "test");

        ExportResult result = exporter.export(surface, sessionRepo.snapshot(), null, null, null,
                noTimestamps);
        String md = result.artifacts().get(0).content();
        assertTrue(md.contains("## Session Profiles"));
        // Timestamps should show "-" instead of actual dates
        long dashCount = md.lines().filter(l -> l.contains("| - |")).count();
        assertTrue(dashCount > 0);
    }

    // ---- Redaction ----------------------------------------------------------

    @Test
    void redactPlaceholdersReplacesTokens() {
        PayloadAssemblyResult payloads = buildPayloadResult();

        ExportOptions redacted = new ExportOptions(
                true, true, true, true, true, true, true, "test");

        ExportResult result = exporter.export(surface, List.of(), null, null, payloads,
                redacted);
        String md = result.artifacts().get(0).content();
        // Placeholders should be replaced with [REDACTED]
        assertFalse(md.contains("<TARGET_ENTITY_ID>"));
        assertTrue(md.contains("[REDACTED]"));
    }

    @Test
    void noRedactByDefaultPreservesPlaceholders() {
        PayloadAssemblyResult payloads = buildPayloadResult();

        ExportResult result = exporter.export(surface, List.of(), null, null, payloads,
                ExportOptions.DEFAULTS);
        String md = result.artifacts().get(0).content();
        assertTrue(md.contains("<TARGET_ENTITY_ID>"));
    }

    // ---- Summary Statistics -------------------------------------------------

    @Test
    void summaryStatisticsAreAccurate() {
        RiskSignalResult signals = buildSignalResult();

        ExportResult result = exporter.export(surface, List.of(), null, signals, null,
                ExportOptions.DEFAULTS);
        assertTrue(result.totalBytes() > 0);
        long computedTotal = result.artifacts().stream().mapToLong(ExportArtifact::sizeBytes).sum();
        assertEquals(computedTotal, result.totalBytes());
    }

    // ---- File Naming --------------------------------------------------------

    @Test
    void fileNamesUseProjectPrefix() {
        ExportOptions customName = new ExportOptions(
                true, true, true, true, true, true, false, "myproject");

        RiskSignalResult signals = buildSignalResult();
        ExportResult result = exporter.export(surface, List.of(), null, signals, null,
                customName);
        assertTrue(result.artifacts().stream()
                .allMatch(a -> a.fileName().startsWith("myproject-")));
    }

    @Test
    void defaultProjectNameUsedWhenBlank() {
        ExportOptions blank = new ExportOptions(
                true, true, true, true, true, true, false, "");

        ExportResult result = exporter.export(surface, List.of(), null, null, null, blank);
        assertTrue(result.artifacts().get(0).fileName().startsWith("methodminer-"));
    }

    // ---- Utility Methods ----------------------------------------------------

    @Test
    void csvEscapeHandlesSpecialCharacters() {
        assertEquals("simple", IntelligenceExporter.csvEscape("simple"));
        assertEquals("\"has,comma\"", IntelligenceExporter.csvEscape("has,comma"));
        assertEquals("\"has\"\"quotes\"\"\"", IntelligenceExporter.csvEscape("has\"quotes\""));
        assertEquals("\"has\nnewline\"", IntelligenceExporter.csvEscape("has\nnewline"));
        assertEquals("", IntelligenceExporter.csvEscape(null));
    }

    @Test
    void jsonEscapeHandlesSpecialCharacters() {
        assertEquals("simple", IntelligenceExporter.jsonEscape("simple"));
        assertEquals("has\\\"quotes\\\"", IntelligenceExporter.jsonEscape("has\"quotes\""));
        assertEquals("has\\nnewline", IntelligenceExporter.jsonEscape("has\nnewline"));
        assertEquals("has\\\\backslash", IntelligenceExporter.jsonEscape("has\\backslash"));
        assertEquals("", IntelligenceExporter.jsonEscape(null));
    }

    @Test
    void formatBytesHandlesRanges() {
        assertEquals("0 B", IntelligenceExporter.formatBytes(0));
        assertEquals("512 B", IntelligenceExporter.formatBytes(512));
        assertEquals("1.0 KB", IntelligenceExporter.formatBytes(1024));
        assertEquals("1.0 MB", IntelligenceExporter.formatBytes(1024 * 1024));
    }

    // ---- ExportArtifact Record Tests ----------------------------------------

    @Test
    void exportArtifactAutoComputesSize() {
        ExportArtifact artifact = ExportArtifact.of("test.md", ExportFormat.MARKDOWN,
                "Hello World", "Test artifact");
        assertEquals(11, artifact.sizeBytes());
        assertEquals("text/markdown", artifact.mimeType());
    }

    // ---- ExportOptions Tests ------------------------------------------------

    @Test
    void exportOptionsDefaults() {
        assertTrue(ExportOptions.DEFAULTS.includeSessions());
        assertTrue(ExportOptions.DEFAULTS.includeComparisons());
        assertTrue(ExportOptions.DEFAULTS.includeRiskSignals());
        assertTrue(ExportOptions.DEFAULTS.includePayloads());
        assertTrue(ExportOptions.DEFAULTS.includeSchemaSummary());
        assertTrue(ExportOptions.DEFAULTS.includeTimestamps());
        assertFalse(ExportOptions.DEFAULTS.redactPlaceholders());
        assertEquals("methodminer", ExportOptions.DEFAULTS.projectName());
    }

    // ---- Test Helpers -------------------------------------------------------

    private static RiskSignalResult buildSignalResult() {
        RiskSignal signal = new RiskSignal(
                UUID.randomUUID(), Instant.now(),
                RiskSignalCategory.ADMIN_ONLY_DELETE,
                "ADMIN-only DELETE: DeleteDevice",
                "DeleteDevice is only observed in ADMIN sessions",
                ProtocolKind.JSON_RPC, "host.com", "/rpc", "DeleteDevice",
                RiskSeverity.HIGH, RiskConfidence.HIGH, 90,
                List.of("ADMIN_ONLY coverage"), "Test with LOW_PRIV credentials",
                Set.of("id"), CoverageStatus.ADMIN_ONLY
        );
        return new RiskSignalResult(Instant.now(), 1, List.of(signal),
                Map.of(RiskSeverity.HIGH, 1),
                Map.of(RiskSignalCategory.ADMIN_ONLY_DELETE, 1));
    }

    private static PayloadAssemblyResult buildPayloadResult() {
        PayloadCandidate candidate = new PayloadCandidate(
                UUID.randomUUID(), Instant.now(), UUID.randomUUID(),
                PayloadCandidateType.ROLE_REPLAY,
                ProtocolKind.JSON_RPC, "host.com", "/rpc",
                "POST", "DeleteDevice",
                "Replay DeleteDevice with LOW_PRIV",
                "Replay the JSON_RPC operation 'DeleteDevice' using LOW_PRIV credentials.",
                "{\n  \"jsonrpc\": \"2.0\",\n  \"method\": \"DeleteDevice\",\n  \"params\": {\n    \"id\": \"<TARGET_ENTITY_ID>\"\n  },\n  \"id\": 1\n}",
                "POST /rpc HTTP/1.1\r\nHost: host.com\r\nContent-Type: application/json\r\nAuthorization: Bearer <LOW_PRIV_AUTH_TOKEN>\r\n\r\n{}",
                "curl -X POST 'https://host.com/rpc' -H 'Content-Type: application/json' -H 'Authorization: Bearer <LOW_PRIV_AUTH_TOKEN>' -d '{}'",
                List.of(new PayloadVariable("authToken", "<LOW_PRIV_AUTH_TOKEN>",
                        "LOW_PRIV session authentication token", "LOW_PRIV", "")),
                "LOW_PRIV",
                "1. Copy the request to Burp Repeater.",
                RiskConfidence.HIGH,
                90
        );
        return new PayloadAssemblyResult(Instant.now(), 1, List.of(candidate),
                Map.of(PayloadCandidateType.ROLE_REPLAY, 1));
    }
}
